module.exports = [
  {
    img: 'punkfairie.net.png',
    github: 'https://github.com/punkfairie/punkfairie-site',
    title: 'punkfairie.net',
    live: 'https://punkfairie.net/',
    description: 'A personal site; includes blinkie collections and a diary (blog).',
    tech: 'Made with Eleventy, SCSS, and PostCSS.',
  },
  {
    img: 'saudade.png',
    github: 'https://github.com/punkfairie/saudade',
    title: 'saudade',
    live: 'https://saudade.punkfairie.net/',
    description: 'An archive of petz/babyz/oddballz sites.',
    tech: 'Made with Gulp, PostCSS, and PostHTML.',
  },
  {
    img: false,
    github: 'https://github.com/punkfairie/ed-safari',
    title: 'ED Safari',
    live: false,
    description: 'Inspired by ED Scout; an exploration tool for the game Elite Dangerous',
    tech: 'Made with Electron, Typescript, and Jest.',
  },
  {
    img: false,
    github: 'https://github.com/punkfairie/codecademy',
    title: 'Codecademy Exercises',
    live: false,
    description: 'Various Codecademy exercises.',
    tech: false,
  },
  {
    img: false,
    github: 'https://github.com/punkfairie/odin-rock-paper-scissors',
    title: 'Odin: Rock, Paper, Scissors',
    live: false,
    description: 'The Odin Project exercise.',
    tech: false,
  },
  {
    img: 'results-summary-component.png',
    github: 'https://github.com/punkfairie/frontend-mentor/tree/main/results-summary-component',
    title: 'Frontend Mentor: Results Summary Component',
    live: 'https://frontend-mentor-gold-five.vercel.app/',
    description: 'Exercise for Frontend Mentor.',
    tech: 'Made with Vite and PostCSS.',
  },
  {
    img: false,
    github: 'https://github.com/punkfairie/frontend-mentor/tree/main/interactive-rating-component',
    title: 'Frontend Mentor: Interactive Rating Component',
    live: false,
    description: 'Exercise for Frontend Mentor.',
    tech: 'Made with Vite, Typescript, and Vue.js.',
  },
  {
    img: 'product-preview-card-component.png',
    github: 'https://github.com/punkfairie/frontend-mentor/tree/main/product-preview-card-component',
    title: 'Frontend Mentor: Product Preview Card',
    live: 'https://product-preview-card-component-zeta-teal.vercel.app/',
    description: 'Exercise for Frontend Mentor.',
    tech: 'Made with Vite.',
  },
  {
    img: false,
    github: 'https://github.com/punkfairie/elite-matrix',
    title: 'Elite Matrix',
    live: false,
    description: 'A small JS/TS library for working with the Elite Dangerous color matrix.',
    tech: 'Made with Typescript.',
  },
]
